services:
  dlist:
    restart: always
    volumes:
      - './data:/opt/alist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    container_name: dlist
    # image: 'ghcr.io/xrgzs/alist:main'
    build:
      context: .
      dockerfile: Dockerfile
